languagelanguage: node_js
node_js:
  - 12
branches:
  only:
    - master
install:
  - npm i
  - npm install -g codecov
cache:
  directories:
    - node_modules
script:
  - npm run codecov
codecov:
  token: 3b790a08-caeb-4f15-b7cf-ded27b0a3e56